# Generated by Django 4.0 on 2021-12-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('fire_depart', models.CharField(blank=True, max_length=100, null=True)),
                ('police_depart', models.CharField(blank=True, max_length=100, null=True)),
                ('gun_range', models.CharField(blank=True, max_length=100, null=True)),
                ('food_near', models.CharField(blank=True, max_length=100, null=True)),
                ('dollar_stor_near', models.CharField(blank=True, max_length=100, null=True)),
                ('pawn_shop', models.CharField(blank=True, max_length=100, null=True)),
                ('homeless_shleter', models.CharField(blank=True, max_length=100, null=True)),
                ('bike_path', models.CharField(blank=True, max_length=100, null=True)),
                ('army_recruiter', models.CharField(blank=True, max_length=100, null=True)),
                ('chinese_restaurant', models.CharField(blank=True, max_length=100, null=True)),
                ('equestrian_path', models.CharField(blank=True, max_length=100, null=True)),
                ('golf_course', models.CharField(blank=True, max_length=100, null=True)),
                ('country_club', models.CharField(blank=True, max_length=100, null=True)),
                ('starbucks', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
